repos:
- repo: https://github.com/guy-av/flutter-format-pre-commit
  rev: "3f799e8fe06fdc62a12b0acbdffc6870ceb23750"
  hooks:
    - id: flutter-format

- repo: https://github.com/fluttercommunity/import_sorter
  rev: 'f350497a11b1285c695595049e95a420068e7a9f'
  hooks:
    - id: flutter-import-sorter